### ISSUE TITLE
Uncaught TypeError: Cannot read property '_data' of undefined

### ISSUE THREAD

**Issue by kiki-lamb** [jsmecham/atom-terminal-tab#109]
[Enter steps to reproduce:]

1. Horizontally resize the pane by dragging it's edge while running a curses app (irssi inside screen) and this error appears.
2. ...

**Atom**: 1.35.1 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.10.5
**Thrown From**: [terminal-tab](https://github.com/jsmecham/atom-terminal-tab) package 0.5.7

### Stack Trace

Uncaught TypeError: Cannot read property '_data' of undefined

```
At /Users/katherinem13/.atom/packages/terminal-tab/node_modules/xterm/lib/BufferLine.js:165

TypeError: Cannot read property '_data' of undefined
    at BufferLine.copyCellsFrom (/packages/terminal-tab/node_modules/xterm/lib/BufferLine.js:165:27)
    at Buffer._reflowSmaller (/packages/terminal-tab/node_modules/xterm/lib/Buffer.js:257:45)
    at Buffer._reflow (/packages/terminal-tab/node_modules/xterm/lib/Buffer.js:177:18)
    at Buffer.resize (/packages/terminal-tab/node_modules/xterm/lib/Buffer.js:152:18)
    at BufferSet.resize (/packages/terminal-tab/node_modules/xterm/lib/BufferSet.js:78:22)
    at Terminal.resize (/packages/terminal-tab/node_modules/xterm/lib/Terminal.js:1108:22)
    at Terminal.resize (/packages/terminal-tab/node_modules/xterm/lib/public/Terminal.js:53:20)
    at Object.fit (/packages/terminal-tab/node_modules/xterm/lib/addons/fit/fit.js:33:18)
    at TerminalView.didResize (/packages/terminal-tab/lib/terminal-view.js:84:11)
```

### Commands

```
     -7:35.1.0 core:close (select#terminal-tab.defaultLocation.form-control)
     -5:32.2.0 application:show-settings (textarea.xterm-helper-textarea)
     -5:13.8.0 terminal:clear (textarea.xterm-helper-textarea)
     -5:06.7.0 window:focus-pane-on-right (input.hidden-input)
     -5:04.6.0 window:focus-pane-on-left (input.hidden-input)
     -3:25 pane:split-down-and-copy-active-item (canvas.xterm-cursor-layer)
     -3:22.4.0 terminal:open (atom-pane.pane.active.hey-pane-focus)
     -3:12.3.0 tree-view:toggle (textarea.xterm-helper-textarea)
  2x -1:29.6.0 window:decrease-font-size (input.hidden-input)
     -1:26.8.0 window:increase-font-size (input.hidden-input)
     -1:20.5.0 application:show-settings (input.hidden-input)
  4x -1:02.7.0 core:backspace (input.hidden-input)
     -0:39.6.0 core:close (input.hidden-input)
     -0:30.5.0 application:show-settings (input.hidden-input)
     -0:26 core:backspace (input.hidden-input)
     -0:22.3.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
acid-syntax 1.0.0 
aemi-dark-syntax 1.0.2 
aemi-dark-ui 1.0.3 
atom-beautify 0.33.4 
atomic-emacs 0.13.0 
autocomplete-clang 0.11.5 
autohide-tree-view 0.25.1 
awesome-dark-syntax 0.3.0 
ayu-dark-syntax 0.1.0 
build 0.70.0 
busy-signal 2.0.1 
file-icons 2.1.31 
glacier-dark-syntax 0.8.0 
glacier-dark-ui 1.5.0 
glacier-darkula-syntax 1.3.3 
glacier-darkula-ui 1.0.5 
hey-pane 1.1.2 
highlight-selected 0.16.0 
intentions 1.1.5 
language-ini 1.20.0 
linter 2.3.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
nv-dark-syntax 1.4.1 
nv-dark-ui 3.0.8 
pane-split-moves-tab 0.1.0 
platformio-ide 2.3.1 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.1 
scratch 1.3.0 
select-rectangle 1.0.2 
sermon 0.1.6 
simple-panes 1.2.0 
sort-lines 0.19.0 
symbols-tree-view 0.14.0 
terminal-tab 0.5.7 
tool-bar 1.1.11 
zhk-dark-syntax 0.3.1 
```

**Comment by jsmecham** [comment]
Please let me know if this is still happening on the latest release (0.6.0).
