### ISSUE TITLE
Failed to activate terminal-tab: The modulewas compiled against a different Node.js version using NODE_MODULE_VERSION 73. This version of Node.js requires NODE_MODULE_VERSION 80

### ISSUE THREAD

**Issue by sbrl** [jsmecham/atom-terminal-tab#137]
The terminal-tab package has randomly started crashing for me. Error and stack trace:

```
The module '/home/sbrl/.atom/packages/terminal-tab/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
Hide Stack Trace
Error: The module '/home/sbrl/.atom/packages/terminal-tab/node_modules/node-pty-prebuilt-multiarch/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149153)
    at Object.<anonymous> (/home/sbrl/.atom/packages/terminal-tab/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js:26:11)
    at Object.<anonymous> (/home/sbrl/.atom/packages/terminal-tab/node_modules/node-pty-prebuilt-multiarch/lib/unixTerminal.js:278:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149153)
    at Object.<anonymous> (/home/sbrl/.atom/packages/terminal-tab/node_modules/node-pty-prebuilt-multiarch/lib/index.js:13:20)
    at Object.<anonymous> (/home/sbrl/.atom/packages/terminal-tab/node_modules/node-pty-prebuilt-multiarch/lib/index.js:51:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149153)
    at Object.<anonymous> (/home/sbrl/.atom/packages/terminal-tab/lib/terminal-session.js:3:52)
    at Object.<anonymous> (/home/sbrl/.atom/packages/terminal-tab/lib/terminal-session.js:13:37)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:72:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:149153)
    at Object.<anonymous> (/home/sbrl/.atom/packages/terminal-tab/lib/main.js:3:43)
```

**Atom**: 1.56.0 x64
**Electron**: 9.4.4
**OS**: Ubuntu 20.10
**Thrown From**: [terminal-tab](https://github.com/jsmecham/atom-terminal-tab) package 0.6.0

**Comment by AronDerenyi** [comment]
If the error appears in the status-bar then if you click it you'll have the option to rebuild the packages. After you rebuilt and reloaded the packages everything should work fine.

**Comment by sbrl** [comment]
@AronDerenyi it does not appear in the status bar. Furthermore, if I manually open the rebuild screen, I see this:


![Selection_2021-04-24_21:06:01_001_0443722](https://user-images.githubusercontent.com/9929737/115971534-ea295780-a540-11eb-9b63-52fb57a56ae9.png)

....despite the fact that the error is thrown every time Atom starts.
