### ISSUE TITLE
Failed to activate the terminal-tab package (At Cannot find module '../src/babel.config.js')

### ISSUE THREAD

**Issue by p-servus** [jsmecham/atom-terminal-tab#140]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

I reinstalled Atom:

I was changing from **atom/atom** (AUR) <https://github.com/atom/atom> to **atom-community/atom** (AUR) <https://github.com/atom-community/atom> using Pamac-GUI.
Because:
  > Atom and all repositories under Atom will be archived on December 15, 2022. [official announcement](https://github.blog/2022-06-08-sunsetting-atom/)

Now i get the error: **Failed to activate the terminal-tab package (At Cannot find module '../src/babel.config.js')**

I also posted the Bug here: <https://github.com/atom-community/atom/issues/460>

I hope some one can hep me .. Thx

### Steps to Reproduce

* I uninstalled old Atom (from **atom/atom** from AUR with Pamac-GUI <https://github.com/atom/atom>)
* I installed "new" Atom (from **atom-community/atom** from AUR with Pamac-GUI <https://github.com/atom-community/atom>)
* The installation of Atom runs with no errors, the following Error was shown: **Failed to activate the terminal-tab package (At Cannot find module '../src/babel.config.js')**
* Then i uninstalled the "terminal-tab package"
* Then i installed the "terminal-tab package" again:
  * but same error: **Failed to activate the terminal-tab package (At Cannot find module '../src/babel.config.js')**

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.63.0-dev-879065cb8 x64
**Electron**: 11.5.0
**OS**: "Manjaro Linux"
**Thrown From**: [terminal-tab](https://github.com/jsmecham/atom-terminal-tab) package 0.6.0

### Stack Trace

Failed to activate the terminal-tab package

```
At Cannot find module '../src/babel.config.js'
Require stack:
- /opt/atom-community/resources/app.asar/node_modules/@babel/core/lib/config/files/configuration.js
- /opt/atom-community/resources/app.asar/node_modules/@babel/core/lib/config/files/index.js
- /opt/atom-community/resources/app.asar/node_modules/@babel/core/lib/index.js
- /opt/atom-community/resources/app.asar/static/index.html

Error: Cannot find module '../src/babel.config.js'
Require stack:
- /opt/atom-community/resources/app.asar/node_modules/@babel/core/lib/config/files/configuration.js
- /opt/atom-community/resources/app.asar/node_modules/@babel/core/lib/config/files/index.js
- /opt/atom-community/resources/app.asar/node_modules/@babel/core/lib/index.js
- /opt/atom-community/resources/app.asar/static/index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at o._resolveFilename (electron/js2c/renderer_init.js:35:917)
    at Function.get_Module._resolveFilename (/opt/atom-community/resources/app/static/<embedded>:11:157942)
    at require.resolve (/opt/atom-community/resources/app/static/<embedded>:11:149312)
    at loadConfig (/app.asar/node_modules/@babel/core/lib/config/files/configuration.js:172:5)
    at loadConfig.next (<anonymous>)
    at buildRootChain (/app.asar/node_modules/@babel/core/lib/config/config-chain.js:80:47)
    at buildRootChain.next (<anonymous>)
    at loadPrivatePartialConfig (/app.asar/node_modules/@babel/core/lib/config/partial.js:103:62)
    at loadPrivatePartialConfig.next (<anonymous>)
    at loadFullConfig (/app.asar/node_modules/@babel/core/lib/config/full.js:57:46)
    at loadFullConfig.next (<anonymous>)
    at Object.transform (/app.asar/node_modules/@babel/core/lib/transform.js:23:45)
    at transform.next (<anonymous>)
    at evaluateSync (/app.asar/node_modules/gensync/index.js:251:28)
    at Object.sync (/app.asar/node_modules/gensync/index.js:89:14)
    at Object.e.compile (/opt/atom-community/resources/app/static/<embedded>:11:579023)
    at Object.compile (/opt/atom-community/resources/app/static/<embedded>:11:575960)
    at compileFileAtPath (/opt/atom-community/resources/app/static/<embedded>:11:151057)
    at Object.value [as .js] (/opt/atom-community/resources/app/static/<embedded>:11:153473)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:72:18)
    at customRequire (/opt/atom-community/resources/app/static/<embedded>:1:756255)
    at requireModule (/opt/atom-community/resources/app/src/atom-environment.js:547:172808)
    at Package.requireMainModule (/opt/atom-community/resources/app/src/atom-environment.js:527:2583701)
    at Package.activateNow (/opt/atom-community/resources/app/src/atom-environment.js:527:2571700)
    at /opt/atom-community/resources/app/src/atom-environment.js:527:2571478
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 2.0.1 
fix-indent-on-paste 0.1.1 
intentions 2.1.1 
linter 3.4.0 
linter-jsonlint 1.4.0 
linter-ui-default 3.4.1 
minimap 4.40.1 
minimap-codeglance 0.4.7 
multi-cursor 3.0.0 
terminal-tab 0.6.0 
```

**Comment by p-servus** [comment]
here is an other one with the same bug for the linter-flake8 package: https://github.com/AtomLinter/linter-flake8/issues/767

.. but here are the most comments for this bug: https://github.com/atom-community/atom/issues/460
