### ISSUE TITLE
Uncaught TypeError: activeTerminalView.clear is not a function

### ISSUE THREAD

**Issue by griley** [jsmecham/atom-terminal-tab#19]
To reproduce:

1. Press cmd-k to clear terminal when terminal is in focus

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [atom-terminal-tab](https://github.com/jsmecham/atom-terminal-tab) package 0.2.2

### Stack Trace

Uncaught TypeError: activeTerminalView.clear is not a function

```
At /Users/griley/.atom/packages/atom-terminal-tab/lib/terminal.js:58

TypeError: activeTerminalView.clear is not a function
    at Object.handleClear (/packages/atom-terminal-tab/lib/terminal.js:58:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at KeymapManager.module.exports.KeymapManager.terminatePendingState (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:591:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:449:27)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -7:20.6.0 core:backspace (input.hidden-input)
  2x -7:19.2.0 core:save (input.hidden-input)
     -3:36.4.0 pane:split-up-and-copy-active-item (input.hidden-input)
  2x -3:28.5.0 core:move-up (input.hidden-input)
     -3:26.2.0 core:move-down (input.hidden-input)
  2x -3:25.7.0 editor:move-to-first-character-of-line (input.hidden-input)
  7x -3:24.4.0 core:select-down (input.hidden-input)
     -3:20 snippets:next-tab-stop (input.hidden-input)
     -3:20 snippets:expand (input.hidden-input)
     -3:20 editor:indent (input.hidden-input)
     -3:18.9.0 core:move-up (input.hidden-input)
  7x -3:18.4.0 core:move-down (input.hidden-input)
     -3:16.8.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -3:16.4.0 editor:newline (input.hidden-input)
     -3:14.1.0 core:save (input.hidden-input)
  2x -2:59.2.0 terminal:clear (textarea.xterm-helper-textarea)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-terminal-tab 0.2.2 
build 0.68.0 
busy 0.7.0 
busy-signal 1.4.3 
dash 1.7.1 
flex-tool-bar 0.12.0 
intentions 1.1.2 
language-actionscript3 0.3.0 
language-flex 0.3.0 
language-haml 0.24.5 
language-markdown 0.23.0 
linter 2.2.0 
linter-haml 2.0.1 
linter-rubocop 2.1.1 
linter-ui-default 1.6.2 
minimap 4.28.2 
rspec 0.3.2 
ruby-test 1.0.2 
run-command2 1.12.2 
Sublime-Style-Column-Selection 1.7.4 
tool-bar 1.1.0 
```

**Comment by dcalhoun** [comment]
This actually happened a bit differently for me.

### Steps to Reproduce

1. Open a file in Atom editor
1. Open a terminal in a separate Atom tab
1. Focus the terminal tab
1. <kbd>CMD</kbd> + <kbd>k</kbd>
1. <kbd>CMD</kbd> + <kbd>k</kbd>
1. Focus file tab
1. <kbd>CMD</kbd> + <kbd>k</kbd>

### Expected Result

Nothing happens as <kbd>CMD</kbd> + <kbd>k</kbd> in an editor pane is not bound to an action.

### Actual Result

Atom throws the above reported error.

**Comment by jsmecham** [comment]
Work on this is being tracked in #66. Thanks!
