### ISSUE TITLE
Cannot copy or paste into terminal

### ISSUE THREAD

**Issue by HotelCalifornia** [jsmecham/atom-terminal-tab#21]
1. Select something in the terminal
2. `cmd`+`c`

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [atom-terminal-tab](https://github.com/jsmecham/atom-terminal-tab) package 0.2.2

### Stack Trace

Uncaught TypeError: activeTerminalView.copySelection is not a function

```
At /Users/alex/.atom/packages/atom-terminal-tab/lib/terminal.js:48

TypeError: activeTerminalView.copySelection is not a function
    at Object.handleCopy (/packages/atom-terminal-tab/lib/terminal.js:48:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/alex/Desktop/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Users/alex/Desktop/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/alex/Desktop/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/alex/Desktop/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/alex/Desktop/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Users/alex/Desktop/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -7:18 core:undo (input.hidden-input)
     -7:16.3.0 core:redo (input.hidden-input)
  2x -7:14.1.0 core:save (input.hidden-input)
     -7:08.6.0 core:undo (input.hidden-input)
     -7:06.7.0 core:redo (input.hidden-input)
  6x -7:05.6.0 core:save (input.hidden-input)
     -3:54.2.0 core:undo (input.hidden-input)
     -3:52.5.0 core:redo (input.hidden-input)
     -3:49.6.0 core:cut (input.hidden-input)
  5x -3:48.6.0 core:backspace (input.hidden-input)
  2x -3:45.8.0 core:move-down (input.hidden-input)
     -3:43.9.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -3:43.9.0 editor:newline (input.hidden-input)
     -3:42.8.0 core:paste (input.hidden-input)
     -3:41.8.0 core:save (input.hidden-input)
     -0:02.5.0 terminal:copy (div.terminal.xterm.xterm-theme-default)
```

When attempting to paste...

1. Have something in the clipboard
2. `cmd`+`v` in the terminal

### Stack Trace

Uncaught TypeError: activeTerminalView.pasteFromClipboard is not a function

```
At /Users/alex/.atom/packages/atom-terminal-tab/lib/terminal.js:53

TypeError: activeTerminalView.pasteFromClipboard is not a function
    at Object.handlePaste (/packages/atom-terminal-tab/lib/terminal.js:53:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/alex/Desktop/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Users/alex/Desktop/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/alex/Desktop/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/alex/Desktop/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/alex/Desktop/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Users/alex/Desktop/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  2x -8:34.8.0 core:save (input.hidden-input)
     -8:29.3.0 core:undo (input.hidden-input)
     -8:27.4.0 core:redo (input.hidden-input)
  6x -8:26.2.0 core:save (input.hidden-input)
     -5:14.9.0 core:undo (input.hidden-input)
     -5:13.2.0 core:redo (input.hidden-input)
     -5:10.3.0 core:cut (input.hidden-input)
  5x -5:09.3.0 core:backspace (input.hidden-input)
  2x -5:06.5.0 core:move-down (input.hidden-input)
     -5:04.6.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -5:04.6.0 editor:newline (input.hidden-input)
     -5:03.5.0 core:paste (input.hidden-input)
     -5:02.5.0 core:save (input.hidden-input)
     -1:23.2.0 terminal:copy (div.terminal.xterm.xterm-theme-default)
     -0:05.9.0 core:copy (input.hidden-input)
     -0:04.0 terminal:paste (textarea.xterm-helper-textarea)
```

**Comment by jsmecham** [comment]
Please test again with the latest release (0.5.0). If you are still seeing this behavior, please feel free to reopen this issue.
