### ISSUE TITLE
Failed to load the atom-terminal-tab package

### ISSUE THREAD

**Issue by midorock2009** [jsmecham/atom-terminal-tab#32]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-terminal-tab](https://github.com/jsmecham/atom-terminal-tab) package 0.2.2

### Stack Trace

Failed to load the atom-terminal-tab package

```
At ENOENT: no such file or directory, open '/Users/muhmmed-abd-alkhalik/.atom/packages/atom-terminal-tab/styles/xterm.less'

Error: ENOENT: no such file or directory, open '/Users/muhmmed-abd-alkhalik/.atom/packages/atom-terminal-tab/styles/xterm.less'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Proxy.fs.readFileSync (fs.js:468:33)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:506:29)
    at ThemeManager.loadLessStylesheet (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:276:54)
    at ThemeManager.loadStylesheet (/Applications/Atom.app/Contents/Resources/app/src/theme-manager.js:246:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:578:60
    at Array.map (native)
    at Package.module.exports.Package.loadStylesheets (/Applications/Atom.app/Contents/Resources/app/src/package.js:576:65)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:152:25
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:145:18)
    at PackageManager.loadAvailablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:618:16)
    at PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:551:25)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:689:23)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
  2x -8:47.2.0 core:select-all (input.hidden-input)
     -8:41.4.0 core:paste (input.hidden-input)
     -8:40.7.0 core:backspace (input.hidden-input)
     -8:40.4.0 core:confirm (input.hidden-input)
     -8:31.9.0 application:new-file (input.hidden-input)
     -8:30.8.0 core:close (input.hidden-input)
     -8:29 application:new-window (div.panels-item)
     -8:25.2.0 core:close (input.hidden-input)
     -8:01.2.0 core:select-all (input.hidden-input)
     -8:00.9.0 core:paste (input.hidden-input)
 12x -8:00.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-terminal-tab 0.2.2 
emmet 2.4.3 
```

**Comment by jsmecham** [comment]
Please test again with the latest release (0.5.0). If you are still seeing this behavior, please feel free to reopen this issue.
