### ISSUE TITLE
Uncaught Error: This socket is closed

### ISSUE THREAD

**Issue by lee-dohm** [jsmecham/atom-terminal-tab#45]
### Steps to Reproduce

1. Launch Atom
2. Toggle Terminal Tab open
3. Wait for ready cursor
4. Type `exit`

**Actual:** :boom:
**Expected:** No :boom: and tab to close

**Atom**: 1.25.0-dev-aea7041c4 x64
**Electron**: 1.7.10
**OS**: Mac OS X 10.13.2
**Thrown From**: [terminal-tab](https://github.com/jsmecham/atom-terminal-tab) package 0.3.4

### Stack Trace

Uncaught Error: This socket is closed

```
At /Users/Lee/.atom/packages/terminal-tab/node_modules/node-pty/lib/unixTerminal.js:108

Error: This socket is closed
    at PipeSocket.Socket._writeGeneric (net.js:692:19)
    at PipeSocket.Socket._write (net.js:743:8)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at PipeSocket.Writable.write (_stream_writable.js:241:11)
    at PipeSocket.Socket.write (net.js:670:40)
    at UnixTerminal.write (/packages/terminal-tab/node_modules/node-pty/lib/unixTerminal.js:181:22)
    at /packages/terminal-tab/lib/terminal-view.js:56:23)
    at Terminal.EventEmitter.emit (/packages/terminal-tab/node_modules/xterm/lib/EventEmitter.js:49:20)
    at Terminal.handler (/packages/terminal-tab/node_modules/xterm/lib/xterm.js:1432:10)
    at Terminal.keyDown (/packages/terminal-tab/node_modules/xterm/lib/xterm.js:930:10)
    at /packages/terminal-tab/node_modules/xterm/lib/xterm.js:365:14)
```

### Commands

```
     -4:42.4.0 core:save (input.hidden-input)
     -4:39.2.0 core:backspace (input.hidden-input)
     -4:37.1.0 core:save (input.hidden-input)
     -4:12 window:toggle-dev-tools (textarea.xterm-helper-textarea)
     -3:54.4.0 settings-view:open (textarea.xterm-helper-textarea)
     -3:07.1.0 window:toggle-dev-tools (textarea.xterm-helper-textarea)
     -1:51.9.0 docblockr:parse-enter (input.hidden-input)
     -1:51.9.0 editor:newline (input.hidden-input)
     -1:51.4.0 docblockr:parse-enter (input.hidden-input)
     -1:51.4.0 editor:newline (input.hidden-input)
     -1:47.4.0 docblockr:parse-enter (input.hidden-input)
     -1:47.4.0 editor:newline (input.hidden-input)
     -1:43.1.0 core:save (input.hidden-input)
  4x -1:05.4.0 core:select-down (input.hidden-input)
     -1:04.5.0 core:backspace (input.hidden-input)
     -1:03.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-2048 3.1.0 
atom-ide-ui 0.7.1 
autocomplete-emojis 2.5.0 
autocomplete-html-entities 0.2.0 
badges 2.2.5 
block-travel 1.0.5 
bug-report 0.7.1 
convert-date 0.1.1 
docblockr 0.13.5 
double-tag 1.1.0 
duotone-dark-syntax 2.1.0 
duotone-light-syntax 2.1.0 
file-icons 2.1.15 
file-type-icons 1.3.4 
fortune-background-tips 1.0.2 
github-atom-light-syntax 0.5.0 
highlight-selected 0.13.1 
ide-css 0.2.0 
ide-rust 0.8.0 
ide-typescript 0.7.2 
indentation-indicator 1.1.0 
language-diff 0.7.0 
language-elixir 0.20.3 
language-generic-config 1.4.0 
language-pegjs 0.5.0 
language-rust 0.4.12 
language-slime 0.0.0 
less-than-slash 0.17.0 
markdown-helper 0.3.0 
minimap 4.29.7 
npm-library-description 1.0.1 
package-sync 1.1.0 
pretty-json 1.6.4 
red-wavy-underline 0.3.3 
right-case 0.2.0 
set-syntax 0.4.0 
significant-other 0.4.0 
soft-wrap-indicator 1.1.0 
sort-lines 0.18.0 
tabs-to-spaces 1.0.3 
teletype 0.5.0 
terminal-tab 0.3.4 
toggle-quotes 1.1.0 
town-crier 0.2.1 
tree-view-git-status 1.4.0 
```

**Comment by jsmecham** [comment]
Hi @lee-dohm, can you please test again with the 0.5.0 release? I'm not able to reproduce this issue...

**Comment by lee-dohm** [comment]
Reproduced on the v0.5.0 release:

1. Launch Atom
2. Toggle terminal tab open
1. Wait for ready cursor
1. Type `exit` and press <kbd>Enter</kbd>
1. Press <kbd>Enter</kbd> again (this is a bug that I see in Hyper too, I assume it's coming from the underlying library you both use?)

**Actual:** :boom:
**Expected:** No :boom: and tab to close

**Atom**: 1.25.0-dev-47f17de5f x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [terminal-tab](https://github.com/jsmecham/atom-terminal-tab) package 0.5.0


### Stack Trace

Uncaught Error: This socket is closed

```
At /Users/Lee/.atom/packages/terminal-tab/node_modules/node-pty-prebuilt/lib/unixTerminal.js:109

Error: This socket is closed
    at PipeSocket.Socket._writeGeneric (net.js:692:19)
    at PipeSocket.Socket._write (net.js:743:8)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at PipeSocket.Writable.write (_stream_writable.js:241:11)
    at PipeSocket.Socket.write (net.js:670:40)
    at UnixTerminal.write (/packages/terminal-tab/node_modules/node-pty-prebuilt/lib/unixTerminal.js:182:22)
    at /packages/terminal-tab/lib/terminal-session.js:28:23)
    at Terminal.EventEmitter.emit (/packages/terminal-tab/node_modules/xterm/lib/EventEmitter.js:39:20)
    at Terminal.handler (/packages/terminal-tab/node_modules/xterm/lib/Terminal.js:1370:14)
    at Terminal._keyDown (/packages/terminal-tab/node_modules/xterm/lib/Terminal.js:863:14)
    at /packages/terminal-tab/node_modules/xterm/lib/Terminal.js:325:19)
```

### Commands

```
     -0:32 command-palette:toggle (input.hidden-input)
     -0:30.5.0 core:confirm (input.hidden-input)
     -0:30.5.0 terminal:open (input.hidden-input)
     -0:06.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-2048 3.1.0 
atom-ide-ui 0.8.1 
autocomplete-emojis 2.5.0 
autocomplete-html-entities 0.2.0 
badges 2.2.5 
block-travel 1.0.5 
bug-report 0.7.1 
convert-date 0.1.1 
docblockr 0.13.6 
double-tag 1.1.0 
duotone-dark-syntax 2.1.0 
duotone-light-syntax 2.1.0 
file-icons 2.1.16 
file-type-icons 1.3.4 
fortune-background-tips 1.0.2 
github-atom-light-syntax 0.5.0 
highlight-selected 0.13.1 
ide-css 0.2.0 
ide-rust 0.11.2 
ide-typescript 0.7.2 
indentation-indicator 1.1.0 
language-diff 0.7.0 
language-elixir 0.22.0 
language-generic-config 1.4.0 
language-pegjs 0.5.0 
language-rust 0.4.12 
language-slime 0.0.0 
less-than-slash 0.18.0 
markdown-helper 0.3.0 
minimap 4.29.7 
npm-library-description 1.0.1 
package-sync 1.1.0 
pretty-json 1.6.4 
red-wavy-underline 0.3.3 
right-case 0.2.0 
set-syntax 0.4.0 
significant-other 0.4.0 
soft-wrap-indicator 1.1.0 
sort-lines 0.18.0 
tabs-to-spaces 1.0.3 
teletype 0.7.0 
terminal-tab 0.5.0 
toggle-quotes 1.1.0 
town-crier 0.2.1 
tree-view-git-status 1.4.0 
```

**Comment by lee-dohm** [comment]
I also got it when running with only terminal-tab and red-wavy-underline installed (red-wavy-underline is referenced in my stylesheet, so I included it):

**Atom**: 1.25.0-dev-47f17de5f x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.3
**Thrown From**: [terminal-tab](https://github.com/jsmecham/atom-terminal-tab) package 0.5.0


### Stack Trace

Uncaught Error: This socket is closed

```
At /Users/Lee/.atom/packages/terminal-tab/node_modules/node-pty-prebuilt/lib/unixTerminal.js:109

Error: This socket is closed
    at PipeSocket.Socket._writeGeneric (net.js:692:19)
    at PipeSocket.Socket._write (net.js:743:8)
    at doWrite (_stream_writable.js:329:12)
    at writeOrBuffer (_stream_writable.js:315:5)
    at PipeSocket.Writable.write (_stream_writable.js:241:11)
    at PipeSocket.Socket.write (net.js:670:40)
    at UnixTerminal.write (/packages/terminal-tab/node_modules/node-pty-prebuilt/lib/unixTerminal.js:182:22)
    at /packages/terminal-tab/lib/terminal-session.js:28:23)
    at Terminal.EventEmitter.emit (/packages/terminal-tab/node_modules/xterm/lib/EventEmitter.js:39:20)
    at Terminal.handler (/packages/terminal-tab/node_modules/xterm/lib/Terminal.js:1370:14)
    at Terminal._keyDown (/packages/terminal-tab/node_modules/xterm/lib/Terminal.js:863:14)
    at /packages/terminal-tab/node_modules/xterm/lib/Terminal.js:325:19)
```

### Commands

```
     -0:11.7.0 command-palette:toggle (input.hidden-input)
     -0:09.7.0 core:confirm (input.hidden-input)
     -0:09.7.0 terminal:open (input.hidden-input)
```

### Non-Core Packages

```
red-wavy-underline 0.3.3 
terminal-tab 0.5.0 
```

**Comment by jsmecham** [comment]
What shell are you using? I've tried this both with Zsh (my default) and Bash. Other than that, we're both on OS X so we'll need to find other differences so I can replicate this...

**Comment by lee-dohm** [comment]
I'm using Zsh v5.4.2 installed via Homebrew.

**Comment by lee-dohm** [comment]
I'll try loading it with a clean environment just in case it is something I'm doing in my `~/.zshrc`.

**Comment by lee-dohm** [comment]
Still got it with all lines commented out in my `~/.zshrc`.

**Comment by brycefranzen** [comment]
MAC OSX HIGH SIERRA
I have this issue as well. Occurred after atom 1.25 update.  Type `exit` then press `ENTER`.
