### ISSUE TITLE
Uncaught TypeError: Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by kdnk** [jsmecham/atom-terminal-tab#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0-beta3 x64
**Electron**: 1.3.14
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-terminal-tab](https://github.com/jsmecham/atom-terminal-tab) package 0.2.0

### Stack Trace

Uncaught TypeError: Cannot set property '0' of undefined

```
At /Users/kdnk/.atom/packages/atom-terminal-tab/node_modules/xterm/lib/InputHandler.js:54

TypeError: Cannot set property '0' of undefined
    at InputHandler.addChar (/packages/atom-terminal-tab/node_modules/xterm/lib/InputHandler.js:54:61)
    at Parser.parse (/packages/atom-terminal-tab/node_modules/xterm/lib/Parser.js:177:44)
    at Terminal.innerWrite (/packages/atom-terminal-tab/node_modules/xterm/lib/xterm.js:809:21)
    at /packages/atom-terminal-tab/node_modules/xterm/lib/xterm.js:794:18
```

### Commands

```
  6x -0:52.6.0 vim-mode-plus:move-up-screen (input.hidden-input)
     -0:50.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-panda-syntax.theme-one-dark-ui)
  8x -0:46.9.0 vim-mode-plus:move-down-screen (input.hidden-input)
  5x -0:46.3.0 vim-mode-plus:move-up-screen (input.hidden-input)
 10x -0:45.9.0 vim-mode-plus:move-down-screen (input.hidden-input)
 10x -0:45.3.0 vim-mode-plus:move-up-screen (input.hidden-input)
     -0:43.8.0 vim-mode-plus:insert-below-with-newline (input.hidden-input)
     -0:43.6.0 editor:newline (input.hidden-input)
     -0:40.6.0 core:backspace (input.hidden-input)
     -0:39.4.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
  4x -0:39.1.0 vim-mode-plus:delete (input.hidden-input)
     -0:38.4.0 core:save (input.hidden-input)
     -0:38.1.0 vim-mode-plus:move-up-screen (input.hidden-input)
     -0:37.6.0 command-palette:toggle (input.hidden-input)
     -0:35.1.0 core:confirm (input.hidden-input)
  3x -0:35.1.0 terminal:open (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-fuzzy-grep 0.16.0 
atom-material-ui 1.3.10 
atom-panda-syntax 0.18.0 
atom-terminal-tab 0.2.0 
autoclose-html 0.23.0 
autocomplete-modules 1.6.9 
base16-ocean-dark-spacegray 0.13.0 
busy-signal 1.4.1 
chester-atom-syntax 0.1.1 
climate-syntax 5.0.0 
climate-ui 4.5.1 
cobalt2-syntax 0.5.1 
css-snippets 1.1.0 
cursor-history 0.9.1 
double-tag 0.8.0 
emmet 2.4.3 
file-icons 2.1.4 
git-diff-details 1.4.0 
git-plus 7.7.0 
hey-pane 0.3.1 
highlight-column 0.5.2 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.57.7 
language-haml 0.24.1 
linter 2.1.4 
linter-eslint 8.1.6 
linter-scss-lint 3.1.0 
linter-ui-default 1.2.3 
minimap 4.27.1 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-selection 4.4.0 
open-this 0.4.0 
pigments 0.39.1 
project-manager 3.3.4 
regex-railroad-diagram 0.17.0 
seti-icons 1.4.3 
seti-syntax 1.1.3 
seti-ui 1.7.0 
slime 2.1.0 
solarized-dark-ui 0.3.2 
sync-settings 0.8.1 
tree-view-autoresize 1.6.0 
tree-view-git-status 1.3.1 
vim-mode-plus 0.91.0 
vim-mode-plus-ex-mode 0.9.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vim-mode-plus-move-selected-text 0.10.0 
zentabs 0.8.8 
```

**Comment by jsmecham** [comment]
I am seeing this behavior when doing a `git diff`, which spawns `less`. Anything using `less` seems to trigger this.

**Comment by jsmecham** [comment]
I no longer see this behavior on master with Xterm 3.1. Please test and reopen this if you experience this issue after the forthcoming 0.5.0 release.
