### ISSUE TITLE
Uncaught TypeError: activeSession.clear is not a function

### ISSUE THREAD

**Issue by axcr** [jsmecham/atom-terminal-tab#74]
Clearing terminal window through "Command+K" throw an "Uncaught TypeError: activeSession.clear is not a function" error.

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [terminal-tab](https://github.com/jsmecham/atom-terminal-tab) package 0.5.4

### Stack Trace

Uncaught TypeError: activeSession.clear is not a function

```
At /Users/lex/.atom/packages/terminal-tab/lib/main.js:68

TypeError: activeSession.clear is not a function
    at Object.handleClear (/packages/terminal-tab/lib/main.js:68:19)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at KeymapManager.module.exports.KeymapManager.terminatePendingState (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:602:20)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:460:27)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -0:57.4.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:56 core:move-down (input.hidden-input)
     -0:55.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:55.3.0 editor:select-to-first-character-of-line (input.hidden-input)
     -0:55 core:copy (input.hidden-input)
     -0:54.5.0 core:close (input.hidden-input)
     -0:53.5.0 core:move-down (input.hidden-input)
     -0:53.3.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:52.9.0 editor:select-to-end-of-line (input.hidden-input)
     -0:52.3.0 core:move-up (input.hidden-input)
     -0:52 core:move-right (input.hidden-input)
     -0:51.7.0 editor:select-to-end-of-line (input.hidden-input)
     -0:50.5.0 core:paste (input.hidden-input)
     -0:50.1.0 core:save (input.hidden-input)
  2x -0:05.8.0 terminal:clear (textarea.xterm-helper-textarea)
     -0:04.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
api-docs 0.0.6 
atom-beautify 0.32.0 
atom-browser 0.68.0 
atom-clock 0.1.16 
atom-java-snippets 0.5.1 
atom-live-server 2.2.0 
atom-runner 2.7.1 
atom-test-runner 0.11.1 
atom-typescript 12.3.3 
autoclose-html 0.23.0 
autocomplete-java 1.2.7 
autocomplete-rails-partial 0.2.0 
busy-signal 1.4.3 
css-snippets 1.1.0 
cucumber 0.6.0 
cucumber-autocomplete 0.7.2 
default-language 0.3.1 
editorconfig 2.2.2 
file-icons 2.1.17 
gherkin-table-formatter 0.1.0 
gist 1.1.0 
hex-to-sass 0.4.0 
intentions 1.1.5 
language-gherkin-german 0.5.2 
language-rspec 0.7.0 
language-slim 1.0.0 
language-vue 0.23.1 
linter 2.2.0 
linter-coffeescript 1.0.0 
linter-erb 1.1.0 
linter-javac 1.9.4 
linter-rubocop 2.2.3 
linter-sass-lint 1.8.3 
linter-slim 1.0.0 
linter-ui-default 1.7.1 
linter-write-good 0.9.0 
open-in-browser 0.5.2 
pigments 0.40.2 
platformio-ide-terminal 2.8.0 
rails-i18n-autocomplete 0.4.0 
rails-i18n-plus 0.5.0 
rails-routes 0.1.5 
railscast-theme 0.4.0 
regex-railroad-diagram 0.19.4 
script 3.18.0 
set-syntax 0.4.0 
sort-lines 0.18.0 
sorter 1.1.0 
tab-numbers 0.6.1 
terminal-tab 0.5.4 
tool-bar 1.1.6 
toolbar-iconshortcuts 3.17.0 
tree-view-autoresize 2.3.0 
tree-view-git-status 1.4.0 
zentabs 0.8.9 
```

**Comment by jsmecham** [comment]
This is due to Atom using cmd-k as a combination shortcut. This will be addressed in #66. Thanks!
