### ISSUE TITLE
Failed to activate the terminal-tab package

### ISSUE THREAD

**Issue by s774977731** [jsmecham/atom-terminal-tab#82]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.0-beta1 x64
**Electron**: 1.7.11
**OS**: Unknown Windows version
**Thrown From**: [terminal-tab](https://github.com/jsmecham/atom-terminal-tab) package 0.5.5

### Stack Trace

Failed to activate the terminal-tab package

```
At A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\fish\.atom\packages\atom-terminal-tab\node_modules\node-pty-prebuilt\build\Release\pty.node

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\fish\.atom\packages\atom-terminal-tab\node_modules\node-pty-prebuilt\build\Release\pty.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.26.0-beta1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-terminal-tab/node_modules/node-pty-prebuilt/lib/windowsPtyAgent.js:9:11)
    at /packages/atom-terminal-tab/node_modules/node-pty-prebuilt/lib/windowsPtyAgent.js:167:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.26.0-beta1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.26.0-beta1/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.26.0-beta1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-terminal-tab/node_modules/node-pty-prebuilt/lib/windowsTerminal.js:18:25)
    at /packages/atom-terminal-tab/node_modules/node-pty-prebuilt/lib/windowsTerminal.js:182:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.26.0-beta1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.26.0-beta1/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.26.0-beta1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-terminal-tab/node_modules/node-pty-prebuilt/lib/index.js:10:16)
    at /packages/atom-terminal-tab/node_modules/node-pty-prebuilt/lib/index.js:53:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.26.0-beta1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.26.0-beta1/resources/app/src/compile-cache.js:240:29)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.30.9 
react-native-snippets 0.3.0 
terminal-tab 0.5.5 
language-vue 0.23.0 
emmet 2.4.3 
language-vue 0.23.0 
react 0.18.0 
terminal-plus 0.14.5 
```

**Comment by edjubuh** [comment]
What version of Windows are you running? Can you provide any steps for what you did to produce this error?

**Comment by jsmecham** [comment]
Does this happen after upgrading between releases?

**Comment by jsmecham** [comment]
https://github.com/jsmecham/atom-terminal-tab/issues/69 might be related, but seems like this error is different.

**Comment by mohita-ajmera** [comment]
I am getting this in ubuntu. I cant install terminal after Atom upgrade.

**Comment by jsmecham** [comment]
Please try again with the latest release (0.6.0).
