### ISSUE TITLE
Uncaught Error: ioctl(2) failed.

### ISSUE THREAD

**Issue by lukepighetti** [jsmecham/atom-terminal-tab#92]
[Enter steps to reproduce:]

1. Open SSH connection
2. type `exit`
3. type `exit`

the terminal tab usually closes on its own

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.2
**Thrown From**: [terminal-tab](https://github.com/jsmecham/atom-terminal-tab) package 0.5.6

### Stack Trace

Uncaught Error: ioctl(2) failed.

```
At /Users/lukepighetti/.atom/packages/terminal-tab/node_modules/node-pty-prebuilt/lib/unixTerminal.js:227

Error: ioctl(2) failed.
    at UnixTerminal.resize (/packages/terminal-tab/node_modules/node-pty-prebuilt/lib/unixTerminal.js:227:13)
    at TerminalView.didResize (/packages/terminal-tab/lib/terminal-view.js:98:24)
```

### Commands

```
     -1:04.0 core:close (textarea.xterm-helper-textarea)
     -1:00.5.0 core:save (input.hidden-input)
  2x -1:00.0 core:close (input.hidden-input)
     -0:41.1.0 core:move-down (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
emmet 2.4.3 
language-babel 2.85.0 
random 1.4.1 
remote-ftp 2.2.0 
terminal-tab 0.5.6 
```

**Comment by jsmecham** [comment]
Let me know if you are still seeing this on 0.6.0.
