### ISSUE TITLE
Uncaught TypeError: Cannot read property 'buffer' of null

### ISSUE THREAD

**Issue by dale-c-anderson** [jsmecham/atom-terminal-tab#97]
### Steps to reproduce:

1. Open a terminal with shift+cmd+T
2. Exit the terminal from the terminal: either with ctrl+d, typing "exit", or "logout. 

The error isn't thrown when using the 'x' at the top right of the terminal tab. 

I see the stack trace mentions xterm library, so I suspect that's where the problem really is, but I'm posting the issue here anyway on the off chance atom-terminal-tab can be made to handle it more gracefully.

**Atom**: 1.23.2 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.5
**Thrown From**: [terminal-tab](https://github.com/jsmecham/atom-terminal-tab) package 0.5.7

### Stack Trace

Uncaught TypeError: Cannot read property 'buffer' of null

```
At /home/someuser/.atom/packages/terminal-tab/node_modules/xterm/lib/InputHandler.js:183

TypeError: Cannot read property 'buffer' of null
    at InputHandler.parse (/packages/terminal-tab/node_modules/xterm/lib/InputHandler.js:183:36)
    at Terminal._innerWrite (/packages/terminal-tab/node_modules/xterm/lib/Terminal.js:841:32)
    at /packages/terminal-tab/node_modules/xterm/lib/Terminal.js:826:23
```

### Commands

```
```

### Non-Core Packages

```
atom-jinja2 0.6.0 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
intentions 1.1.5 
jslint 1.5.1 
linter 2.2.0 
linter-js-standard 5.1.0 
linter-jshint 3.1.8 
linter-ui-default 1.7.1 
open-recent 5.0.0 
split-diff 1.5.2 
terminal-tab 0.5.7 
```

**Comment by ealap** [comment]
Encountered on Windows 10 1803 using all modes of closing the tab including clicking on the 'x' button at the top right of the terminal tab.

Error:
```
C:\Users\someuser\.atom\packages\terminal-tab\node_modules\node-pty-prebuilt\lib\windowsPtyAgent.js:83
```

Stack trace:
```
Error: Pty seems to have been killed already
    at WindowsPtyAgent.kill (C:\Users\someuser\.atom\packages\terminal-tab\node_modules\node-pty-prebuilt\lib\windowsPtyAgent.js:83:13)
    at WindowsTerminal.<anonymous> (C:\Users\someuser\.atom\packages\terminal-tab\node_modules\node-pty-prebuilt\lib\windowsTerminal.js:144:26)
    at WindowsTerminal._defer (C:\Users\someuser\.atom\packages\terminal-tab\node_modules\node-pty-prebuilt\lib\windowsTerminal.js:155:24)
    at WindowsTerminal.kill (C:\Users\someuser\.atom\packages\terminal-tab\node_modules\node-pty-prebuilt\lib\windowsTerminal.js:139:14)
    at TerminalSession.destroy (file:///C:/Users/someuser/.atom/packages/terminal-tab/lib/terminal-session.js:94:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at WindowsTerminal.Terminal.emit (C:\Users\someuser\.atom\packages\terminal-tab\node_modules\node-pty-prebuilt\lib\terminal.js:79:34)
    at Socket.<anonymous> (C:\Users\someuser\.atom\packages\terminal-tab\node_modules\node-pty-prebuilt\lib\windowsTerminal.js:94:23)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
```

**Comment by jsmecham** [comment]
Please let me know if this is still happening on the latest release (0.6.0).
